#
# Makefile for the Linux kernel device drivers.
#
# 2006-04-04, designed by huawei corp.
# written as internal module's Makefile.
#

obj-m += sd_mmc_sdio.o
sd_mmc_sdio-y := $(pwd)/driver_mmc/Host_Drv/host.o \
                 $(pwd)/driver_mmc/Bus_Drv/Bus.o                 
