#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-hismall-linux-gcc -O"
  #define PLATFORM "dist"
  #define DATE "Sat Jul  9 17:10:40 CST 2011"
#endif
