#!/bin/sh
# create by c42025 2008-01-30
# Useage: load3511 [ -r ] [ -i ]
#         -r : rmmod all modules
#         -i : insmod all modules
#    default : rmmod all moules and then insmod them whithout any argument
DBG="n"
MODPROBE=/sbin/modprobe
INSMOD=/sbin/insmod
RMMOD=/sbin/rmmod
LSMOD=/sbin/lsmod

if [ $DBG = "y" ];then
MODPROBE=echo
INSMOD=echo
RMMOD=echo
fi

MPP_KO_DIR=`dirname $0`
FB_MOD_DIR=.
TDE_MOD_DIR=.

MPP_MODULES="hi3511_base
	hi3511_sys
	hi3511_viu
	hi3511_vou
	hi3511_dsu
	hi3511_vpp
	hi3511_venc
	hi3511_group
	hi3511_vdec 
	hi3511_md
	hi3511_sio
	hi3511_ai
	hi3511_ao
	hi3511_chnl
	hi3511_h264e
	hi3511_h264d
	hi3511_jpege
	hi3511_jpegd
	"
CBB_MODULES="tde"
FB_MODULES="hifb"

#EXT_MODULES_LOAD="gpioi2c hidmac tw_2815 adv_7179 tlv_320aic31 tvp_5150"
#EXT_MODULES_UNLOAD="tvp_5150 tlv_320aic31 tw_2815 adv_7179 gpioi2c hidmac"

EXT_MODULES_LOAD="gpioi2c hidmac tw_2815 adv_7179 tlv_320aic31"
EXT_MODULES_UNLOAD="tlv_320aic31 tw_2815 adv_7179 gpioi2c hidmac"

#modlues that will not be insert into kernel
SKIP_MODULES="hi3511_jpegd"

load_ext_modules()
{
	local n
	for n in $EXT_MODULES_LOAD
	do
		$MODPROBE $n || return 1
		echo "insmod $n OK!"
	done
	return 0
}

unload_ext_modules()
{
	local n
	for n in $EXT_MODULES_UNLOAD
	do
		if lsmod |grep -q "$n"
		then
#			echo "rmmod $n ........"
			$RMMOD `basename $n` ||return 1
#			echo "rmmod $n OK!"
		fi
	done
	return 0
}

load()
{
	local n
	for n in $*
	do
		if echo "$SKIP_MODULES" |grep -q "$n"
		then
			continue	
		fi
		if [ $n = "hifb" ]
		then
			$MODPROBE fb || return 1
			$INSMOD "$FB_MOD_DIR/$n.ko" video="hifb:vram0_size=6291456,vram2_size=1024" || return 1
			echo "insmod $n OK!"
			continue
		fi
		if [ $n = "tde" ]
		then
			$INSMOD "$TDE_MOD_DIR/$n.ko" || return 1
			echo "insmod $n OK!"
			continue
		fi
		if [ $n = "hi3511_sys" ]
		then
			$INSMOD "$MPP_KO_DIR/$n.ko" logbuflen=32 || return 1
			echo "insmod $n OK!"
			continue
		fi
		$INSMOD "$MPP_KO_DIR/$n.ko" || return 1
		echo "insmod $n OK!"
	done
	return 0
}


unload()
{
	local n
	for n in $*
	do
		if [ $n = "hi3511_base" ]
		then
			continue;
		fi
		if [ $n = "hi3511_sys" ]
		then
			continue;
		fi
		if lsmod |grep -q "$n"
		then
#			echo "rmmod $n ........!"
			$RMMOD `basename $n` ||return 1
#			echo -e "rmmod $n OK!\n"
		fi

	done
	if ! echo $* |grep -q "hi3511_base"
	then
		return 0
	fi

	if lsmod |grep -q "hi3511_sys"
	then
		$RMMOD hi3511_sys
	fi
	if lsmod |grep -q "hi3511_base"
	then
		$RMMOD hi3511_base 	
	fi
	return 0
}

#********************************
if [ "$1" != "-i" ]
then
	unload $FB_MODULES || exit 1
	unload $MPP_MODULES || exit 1
	unload $CBB_MODULES || exit 1	
	unload_ext_modules || exit 1
fi

if [ "$1" = "-r" ]
then
	exit 0
fi

#********************************
load_ext_modules
if [ $? -ne 0 ]
then
	unload_ext_modules
	exit -1
fi

#********************************
load $CBB_MODULES
if [ $? -ne 0 ]
then
	unload $CBB_MODULES
	exit -1
fi
echo "load succcessed!"

#********************************
load $MPP_MODULES
if [ $? -ne 0 ]
then
	unload $MPP_MODULES
	exit -1
fi
#********************************
load $FB_MODULES
if [ $? -ne 0 ]
then
	unload $FB_MODULES
	exit -1
fi
echo "load succcessed!"

